# Generated by Django 5.0 on 2024-12-18 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoría de Ejercicio',
                'verbose_name_plural': 'Categorías de Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='DiaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Día de Asistencia',
                'verbose_name_plural': 'Días de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField(help_text='Altura en centímetros')),
                ('peso', models.FloatField(help_text='Peso en kilogramos')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dias_asistencia', models.ManyToManyField(blank=True, to='gimnasio.diaasistencia')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('grupo_muscular', models.CharField(default='General', max_length=50)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_profesor', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gimnasio.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticiones', models.CharField(max_length=50)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('descanso', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio de Rutina',
                'verbose_name_plural': 'Ejercicios de Rutina',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='gimnasio.RutinaEjercicio', to='gimnasio.ejercicio'),
        ),
        migrations.CreateModel(
            name='EjercicioCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('series_completadas', models.PositiveIntegerField()),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_completados', to='gimnasio.alumno')),
                ('rutina_ejercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gimnasio.rutinaejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio Completado',
                'verbose_name_plural': 'Ejercicios Completados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mes_correspondiente', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gimnasio.alumno')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-fecha_pago'],
                'unique_together': {('alumno', 'mes_correspondiente')},
            },
        ),
        migrations.CreateModel(
            name='RegistroProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_progreso', to='gimnasio.alumno')),
            ],
            options={
                'verbose_name': 'Registro de Progreso',
                'verbose_name_plural': 'Registros de Progreso',
                'ordering': ['-fecha'],
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
