# Generated by Django 5.1.3 on 2024-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='dias_asistencia',
        ),
        migrations.AddField(
            model_name='alumno',
            name='dias_asistencia',
            field=models.ManyToManyField(to='gimnasio.diaasistencia'),
        ),
    ]
