# Generated by Django 5.0 on 2024-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(default='Nueva Rutina', max_length=100),
        ),
    ]
