# Generated by Django 5.0 on 2024-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_diaasistencia_remove_alumno_dias_asistencia_and_more'),
    ]

    operations = [
    ]
