# Generated by Django 5.0 on 2024-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0003_remove_pagocuota_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
