# Generated by Django 5.0 on 2024-12-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0005_remove_ejercicio_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerutina',
            options={'ordering': ['orden'], 'verbose_name': 'Detalle de Rutina', 'verbose_name_plural': 'Detalles de Rutinas'},
        ),
        migrations.AlterUniqueTogether(
            name='detallerutina',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detallerutina',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutina',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='horario',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], default='Mañana', max_length=20),
        ),
        migrations.CreateModel(
            name='EjercicioCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('series_completadas', models.PositiveIntegerField()),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_completados', to='gimnasio.alumno')),
                ('detalle_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.detallerutina')),
            ],
            options={
                'verbose_name': 'Ejercicio Completado',
                'verbose_name_plural': 'Ejercicios Completados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mes_correspondiente', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gimnasio.alumno')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-fecha_pago'],
                'unique_together': {('alumno', 'mes_correspondiente')},
            },
        ),
        migrations.CreateModel(
            name='RegistroProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_progreso', to='gimnasio.alumno')),
            ],
            options={
                'verbose_name': 'Registro de Progreso',
                'verbose_name_plural': 'Registros de Progreso',
                'ordering': ['-fecha'],
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
